amdblis: fix zen4
I was getting errors like:
```
libflame.so: undefined reference to `bli_dgemv_n_zen4_int_40x2_st'
```
on a zen4 target.

Adding the `zen4` target to the package.py fixed the error.

I also added zen5, assuming it is the same, but I have not tested that.