Patch in re2 header includes
Add patch method to handle missing implicit header includes for GCC 13+ and Clang 15+.

This patch is necessary and sufficient for me to build this spec:
 -   re2@2024-07-02~icu~ipo+pic~shared build_system=cmake build_type=Release generator=make platform=linux os=rhel8 target=zen3 %cxx=gcc@13.4.0 

Without errors like:

 [e]          ^gcc@8.5.0+binutils+bootstrap~graphite+libsanitizer~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages:='c,c++,fortran' platform=linux os=rhel8 target=x86_64

[+]          ^gcc-runtime@8.5.0 build_system=generic platform=linux os=rhel8 target=zen


...and the 'top' of the error output:

[ 73%] Building CXX object CMakeFiles/re2.dir/re2/simplify.cc.o

/storage/users/wspear/bin/SPACK/gilgamesh/spack/opt/spack/linux-zen3/compiler-wrapper-1.0-r533h4sr4uzpv32pv2w4ootpawmxmmgf/libexec/spack/gcc/g++  -I/tmp/wspear/spack-stage/spack-stage-re2-2023-09-01-o2docgedch6htv5uscgaiek7ygdv6gy2/spack-src -isystem /storage/users/wspear/bin/SPACK/gilgamesh/spack/opt/spack/linux-zen3/abseil-cpp-20260107.1-t6vh5x4y757uaf4a7ho3xoa7cayf5fz2/include -O3 -DNDEBUG -std=gnu++17 -fPIC -pthread -MD -MT CMakeFiles/re2.dir/re2/simplify.cc.o -MF CMakeFiles/re2.dir/re2/simplify.cc.o.d -o CMakeFiles/re2.dir/re2/simplify.cc.o -c /tmp/wspear/spack-stage/spack-stage-re2-2023-09-01-o2docgedch6htv5uscgaiek7ygdv6gy2/spack-src/re2/simplify.cc

In file included from /tmp/wspear/spack-stage/spack-stage-re2-2023-09-01-o2docgedch6htv5uscgaiek7ygdv6gy2/spack-src/re2/set.cc:14:

/tmp/wspear/spack-stage/spack-stage-re2-2023-09-01-o2docgedch6htv5uscgaiek7ygdv6gy2/spack-src/re2/prog.h: In member function 'const void* re2::Prog::PrefixAccel(const void*, size_t)':

/tmp/wspear/spack-stage/spack-stage-re2-2023-09-01-o2docgedch6htv5uscgaiek7ygdv6gy2/spack-src/re2/prog.h:230:14: error: 'memchr' was not declared in this scope

  230 |       return memchr(data, prefix_front_, size);

      |              ^~~~~~

/tmp/wspear/spack-stage/spack-stage-re2-2023-09-01-o2docgedch6htv5uscgaiek7ygdv6gy2/spack-src/re2/prog.h:25:1: note: 'memchr' is defined in header '<cstring>'; did you forget to '#include <cstring>'?

   24 | #include "re2/sparse_set.h"

  +++ |+#include <cstring>

   25 |