hip: revert using libs.directories[0] instead of prefix.lib  (#19671)
Currently fails with:

 Error: NoLibrariesError: Unable to recursively locate rocm-device-libs libraries