cargo: fall back to older versions of packages if rust toolchain is old (#3945)
We currently hit issues like this in CI:

```
  error: rustc 1.92.0 is not supported by the following packages:
    fixed@1.31.0 requires rustc 1.93
    fixed@1.31.0 requires rustc 1.93
    fixed@1.31.0 requires rustc 1.93
  Either upgrade rustc or select compatible dependency versions with
  `cargo update <name>@<current-ver> --precise <compatible-ver>`
  where `<compatible-ver>` is the latest version supporting rustc 1.92.0
```

When we are ever so slightly behind the latest rust version. This is because
`cargo` by default picks the latest version of packages without regard to
what rust version we are using. Rust 1.84 and higher have an option for
`cargo` to fall back to older versions of packages when the latest is
incompatible with the current toolchain:

```
export CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS=fallback
```

Setting this in CI should allow us to avoid CI breaking when we aren't quite
at the latest rust version.  Obviously we still want to update, but we also
want stable CI.

There may be packages that don't set their `rust-version` properly in `Cargo.toml`,
so this may not be the end of the story, and we have a long way to go for proper
`rust` integration, but it's a start at least.

- [x] set CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS=fallback in
      `setup_dependent_build_environment` in `rust`

Signed-off-by: Todd Gamblin <tgamblin@llnl.gov>