mozjs: add 140.7.0 and fix build
llvm is required to fix:
```
checking for llvm-objdump... not found
DEBUG: llvm_objdump: Looking for llvm-objdump
ERROR: Cannot find llvm-objdump
```

python@3.14 does not work due to:
```
AttributeError: module 'ast' has no attribute 'Str'
```