py-setuptools: Add dependency to py-packaging
The latest version of py-setuptools depends on a recent version of
py-packaging. If you fail to load a valid version of packaging, you
get an error like the following.

```
  ImportError: Cannot import `packaging.licenses`.
          Setuptools>=77.0.0 requires "packaging>=24.2" to work properly.
          Please make sure you have a suitable version installed.
```

This causes other packages that use pip to install themselves to fail.